### ISSUE TITLE
Minor Readme amendments

### ISSUE THREAD

**Issue by jleavers** [MonsantoCo/cf-metrics#7] opened 2015-10-14 23:42 UTC
First of all - thanks for releasing this - it's very useful!

I came across a couple of (very) minor issues during the setup so thought the Readme could potentially be amended for future readers.

- Heka ports

The readme mentions 8003 & 8004 for CF & bosh, however hekad.toml is actually configured to use the default 2003 (and 2004).

- docker-compose.yml PRE_CREATE_DB

I found that the databases were not created until I changed the syntax as follows:

  environment:
    PRE_CREATE_DB: cf_1;cf_2

Perhaps this is because I am on a newer version of docker (1.8.2) and docker-compose (1.4.2) compared to your original testing?

- Lua Slack filters

I found that having <!channel>\n in the out_message just resulted in "@channel" being added to the Slack message - however as the Slack webhook URL I created specified the channel, I just removed this.

It might also be worth mentioning that as part of the setup, the URLs in the Lua filters should be updated from dockerserver.company.com to the same URL specified in grafana.ini :-) 

Thanks again

**Comment by mjseid** [comment] 2015-11-14 16:24
Thanks so much for your comments!

Sorry it took so long to respond, I wasn't watching notifications from this repo so I didn't notice it until now.  We'll be more responsive in the future.

- Heka ports
	You're right, thanks for pointing this mis-match out.  I've updated the README to make them match.

- docker-compose.yml
	To clarify are you saying you couldn't get it to work until you took away the "-" in front of the PRECREATE?  I've updated to docker (1.8.3) and docker-compose(1.4.2) and tried to reproduce but the syntax I've included in the yml is still creating the databases for me.  

- Lua Slack Fliters
	I've updated the README to mention updating the alert filters with the correct url.  The "@channel" is prepended so that slack alerts every member of the channel that an alert has occurred whether they are currently viewing the channel or not.  We're basically using it as a page-out, but you're right if you don't want or need that you can omit it like you did.  Here's some info on the slack options there for making channel announcements https://slack.zendesk.com/hc/en-us/articles/202009646-Making-announcements

**Comment by jleavers** [comment] 2015-11-18 12:58
Hi,

Yes, I removed the hyphen - my working influxdb section is as follows:

influxdb:
  build: ./influxdb
  ports:
  - "8083:8083"
  - "8084:8084"
  - "8086:8086"
  environment:
    PRE_CREATE_DB: bosh_prod;cf_prod
  #command: /opt/influxdb/influxd restore -config /etc/opt/influxdb/influxdb.config /data/mybak

**Comment by mjseid** [comment] 2015-11-19 15:05
Hm, 
    does it work if you move the hyphen over a couple spaces?  I know at least AWS ECS seems to be more picky about spacing than straight docker for me

```
  environment:
    - PRE_CREATE_DB=cf_np;cf_prd;bosh_np;bosh_prd
```

**Comment by mjseid** [comment] 2015-12-05 23:42
I haven't been able to replicate the issue with the compose yml so I'm closing the issue.  Thanks

**Closed by mjseid** 2015-12-05 23:42 UTC
